#!/usr/bin/dh-exec
debian/55gnome-session_gnomerc etc/X11/Xsession.d
# Handled by desktop-file-utils in Ubuntu
# debian/gnome-mimeapps.list usr/share/applications/
debian/xdg_dirs_desktop_session.sh etc/profile.d
debian/gnome-session_gnomerc.sh etc/profile.d/
[linux-any] usr/lib/systemd/user/gnome-launched-*
[linux-any] usr/lib/systemd/user/gnome-session*.service
[linux-any] usr/lib/systemd/user/gnome-session*.target
usr/share/locale
